Read_HOPr_Mesh3D_t – SELF
Read_HOPr_Mesh3D_t Subroutine
3-Clause BSD with attribution
97 statements
Source File
public subroutine Read_HOPr_Mesh3D_t(this, meshFile)
Arguments
Type Intent Optional Attributes Name
class(Mesh3D_t), intent(out) :: this
character, intent(in) :: meshFile
Calls
Contents
Source Code
Read_HOPr_Mesh3D_t
Source Code
  subroutine Read_HOPr_Mesh3D_t(this,meshFile)
    ! From https://www.hopr-project.org/externals/Meshformat.pdf, Algorithm 6
    implicit none
    class(Mesh3D_t),intent(out) :: this
    character(*),intent(in) :: meshFile
    ! Local
    integer(HID_T) :: fileId
    integer(HID_T) :: offset(1:2),gOffset(1)
    integer :: nGlobalElem
    integer :: firstElem
    integer :: firstNode
    integer :: firstSide
    integer :: nLocalElems
    integer :: nLocalNodes
    integer :: nLocalSides
    integer :: nUniqueSides
    integer :: nGeo,nBCs
    integer :: eid,lsid,iSide
    integer :: i,j,k,nid
    integer,dimension(:,:),allocatable :: hopr_elemInfo
    integer,dimension(:,:),allocatable :: hopr_sideInfo
    real(prec),dimension(:,:),allocatable :: hopr_nodeCoords
    integer,dimension(:),allocatable :: hopr_globalNodeIDs
    integer,dimension(:,:),allocatable :: bcType
    call this%decomp%init()
    if(this%decomp%mpiEnabled) then
      call Open_HDF5(meshFile,H5F_ACC_RDONLY_F,fileId,this%decomp%mpiComm)
    else
      call Open_HDF5(meshFile,H5F_ACC_RDONLY_F,fileId)
    endif
    call ReadAttribute_HDF5(fileId,'nElems',nGlobalElem)
    call ReadAttribute_HDF5(fileId,'Ngeo',nGeo)
    call ReadAttribute_HDF5(fileId,'nBCs',nBCs)
    call ReadAttribute_HDF5(fileId,'nUniqueSides',nUniqueSides)
    ! Read BCType
    allocate(bcType(1:4,1:nBCs))
    if(this%decomp%mpiEnabled) then
      offset(:) = 0
      call ReadArray_HDF5(fileId,'BCType',bcType,offset)
    else
      call ReadArray_HDF5(fileId,'BCType',bcType)
    endif
    ! Read local subarray of ElemInfo
    call this%decomp%GenerateDecomposition(nGlobalElem,nUniqueSides)
    firstElem = this%decomp%offsetElem(this%decomp%rankId+1)+1
    nLocalElems = this%decomp%offsetElem(this%decomp%rankId+2)- &
                  this%decomp%offsetElem(this%decomp%rankId+1)
    ! Allocate Space for hopr_elemInfo!
    allocate(hopr_elemInfo(1:6,1:nLocalElems))
    if(this%decomp%mpiEnabled) then
      offset = (/0,firstElem-1/)
      call ReadArray_HDF5(fileId,'ElemInfo',hopr_elemInfo,offset)
    else
      call ReadArray_HDF5(fileId,'ElemInfo',hopr_elemInfo)
    endif
    ! Read local subarray of NodeCoords and GlobalNodeIDs
    firstNode = hopr_elemInfo(5,1)+1
    nLocalNodes = hopr_elemInfo(6,nLocalElems)-hopr_elemInfo(5,1)
    ! Allocate Space for hopr_nodeCoords and hopr_globalNodeIDs !
    allocate(hopr_nodeCoords(1:3,1:nLocalNodes),hopr_globalNodeIDs(1:nLocalNodes))
    if(this%decomp%mpiEnabled) then
      offset = (/0,firstNode-1/)
      call ReadArray_HDF5(fileId,'NodeCoords',hopr_nodeCoords,offset)
      gOffset = (/firstNode-1/)
      call ReadArray_HDF5(fileId,'GlobalNodeIDs',hopr_globalNodeIDs,gOffset)
    else
      call ReadArray_HDF5(fileId,'NodeCoords',hopr_nodeCoords)
      call ReadArray_HDF5(fileId,'GlobalNodeIDs',hopr_globalNodeIDs)
    endif
    ! Read local subarray of SideInfo
    firstSide = hopr_elemInfo(3,1)+1
    nLocalSides = hopr_elemInfo(4,nLocalElems)-hopr_elemInfo(3,1)
    ! Allocate space for hopr_sideInfo
    allocate(hopr_sideInfo(1:5,1:nLocalSides))
    if(this%decomp%mpiEnabled) then
      offset = (/0,firstSide-1/)
      call ReadArray_HDF5(fileId,'SideInfo',hopr_sideInfo,offset)
    else
      call ReadArray_HDF5(fileId,'SideInfo',hopr_sideInfo)
    endif
    call Close_HDF5(fileID)
    ! ---- Done reading 3-D Mesh information ---- !
    ! Load hopr data into mesh data structure
    call this%Init(nGeo,nLocalElems,nLocalSides,nLocalNodes,nBCs)
    ! Copy data from local arrays into this
    this%elemInfo = hopr_elemInfo
    this%nUniqueSides = nUniqueSides
    this%quadrature = UNIFORM
    ! Grab the node coordinates
    do eid = 1,this%nElem
      do k = 1,nGeo+1
        do j = 1,nGeo+1
          do i = 1,nGeo+1
            nid = i+(nGeo+1)*(j-1+(nGeo+1)*(k-1+(nGeo+1)*(eid-1)))
            this%nodeCoords(1:3,i,j,k,eid) = hopr_nodeCoords(1:3,nid)
            this%globalNodeIDs(i,j,k,eid) = hopr_globalNodeIDs(nid)
          enddo
        enddo
      enddo
    enddo
    iSide = 0
    do eid = 1,this%nElem
      do lsid = 1,6
        iSide = iSide+1
        this%sideInfo(1:5,lsid,eid) = hopr_sideInfo(1:5,iSide)
      enddo
    enddo
    call this%RecalculateFlip()
    deallocate(hopr_elemInfo,hopr_nodeCoords,hopr_globalNodeIDs,hopr_sideInfo)
    call this%UpdateDevice()
  endsubroutine Read_HOPr_Mesh3D_t
Call graph
read_hopr_mesh3d_t calls open_hdf5, readattribute_hdf5, close_hdf5, readarray_hdf5
open_hdf5 calls open_hdf5_parallel, open_hdf5_serial
readattribute_hdf5 calls readattribute_hdf5_real, readattribute_hdf5_character, readattribute_hdf5_int32
close_hdf5 calls h5fclose_f, h5close_f
readarray_hdf5 calls readarray_hdf5_int32_r1_parallel, readarray_hdf5_real_r1_serial, readarray_hdf5_real_r4_serial, readarray_hdf5_real_r1_parallel, readarray_hdf5_real_r3_parallel, readarray_hdf5_int32_r2_parallel, readarray_hdf5_int32_r1_serial, readarray_hdf5_real_r3_serial, readarray_hdf5_real_r2_parallel, readarray_hdf5_real_r4_parallel, readarray_hdf5_real_r5_serial, readarray_hdf5_real_r2_serial, readarray_hdf5_int32_r2_serial
readattribute_hdf5_real calls h5aread_f, h5aclose_f, h5aget_type_f, h5tclose_f, h5aopen_f
readattribute_hdf5_character calls h5aread_f, h5aclose_f, h5aget_type_f, h5tclose_f, h5aopen_f
readarray_hdf5_int32_r1_parallel calls h5screate_simple_f, h5pset_dxpl_mpio_f, h5dget_space_f, h5dclose_f, h5pcreate_f, h5dopen_f, h5dget_type_f, h5tclose_f, h5sselect_hyperslab_f, h5dread_f, h5pclose_f, h5sclose_f
readarray_hdf5_real_r1_serial calls h5kind_to_type, h5dclose_f, h5dopen_f, h5dread_f
readarray_hdf5_real_r4_serial calls h5kind_to_type, h5dclose_f, h5dopen_f, h5dread_f
readarray_hdf5_real_r1_parallel calls h5screate_simple_f, h5pset_dxpl_mpio_f, h5dget_space_f, h5dclose_f, h5pcreate_f, h5dopen_f, h5dget_type_f, h5tclose_f, h5sselect_hyperslab_f, h5dread_f, h5pclose_f, h5sclose_f
readarray_hdf5_real_r3_parallel calls h5screate_simple_f, h5pset_dxpl_mpio_f, h5dget_space_f, h5dclose_f, h5pcreate_f, h5dopen_f, h5dget_type_f, h5tclose_f, h5sselect_hyperslab_f, h5dread_f, h5pclose_f, h5sclose_f
open_hdf5_parallel calls h5open_f, h5pset_fapl_mpio_f, h5fopen_f, h5pcreate_f, h5fcreate_f, h5pclose_f
readarray_hdf5_int32_r2_parallel calls h5screate_simple_f, h5pset_dxpl_mpio_f, h5dget_space_f, h5dclose_f, h5pcreate_f, h5dopen_f, h5dget_type_f, h5tclose_f, h5sselect_hyperslab_f, h5dread_f, h5pclose_f, h5sclose_f
readattribute_hdf5_int32 calls h5aread_f, h5aclose_f, h5aget_type_f, h5tclose_f, h5aopen_f
readarray_hdf5_int32_r1_serial calls h5kind_to_type, h5dclose_f, h5dopen_f, h5dread_f
readarray_hdf5_real_r3_serial calls h5kind_to_type, h5dclose_f, h5dopen_f, h5dread_f
readarray_hdf5_real_r2_parallel calls h5screate_simple_f, h5pset_dxpl_mpio_f, h5dget_space_f, h5dclose_f, h5pcreate_f, h5dopen_f, h5dget_type_f, h5tclose_f, h5sselect_hyperslab_f, h5dread_f, h5pclose_f, h5sclose_f
readarray_hdf5_real_r4_parallel calls h5screate_simple_f, h5pset_dxpl_mpio_f, h5dget_space_f, h5dclose_f, h5pcreate_f, h5dopen_f, h5dget_type_f, h5tclose_f, h5sselect_hyperslab_f, h5dread_f, h5pclose_f, h5sclose_f
open_hdf5_serial calls h5open_f, h5fopen_f, h5fcreate_f
readarray_hdf5_real_r5_serial calls h5kind_to_type, h5dclose_f, h5dopen_f, h5dread_f
readarray_hdf5_real_r2_serial calls h5kind_to_type, h5dclose_f, h5dopen_f, h5dread_f
readarray_hdf5_int32_r2_serial calls h5kind_to_type, h5dclose_f, h5dopen_f, h5dread_f